### ISSUE TITLE
Set up CI for submodules

### ISSUE THREAD

**Issue by ghost** [RaftLib/RaftLib#105]
Use https://raw.githubusercontent.com/f-tischler/RaftLib/9cbea22a1dd613889485be31be047d2c87c632c4/.github/workflows/main.yml as an example.

**Comment by 2noodle** [comment]
Need to setup for 
* Affinity
* Demangle
* ROCV
* SHM
* cmdargs
* QThreads - for this one we probably need to test only Linux, there's also the disabling of the one benchmark that seems to fail, likely due to the exception issue @jonathan-beard mentioned.

**Comment by jonathan-beard** [comment]
## Build status set up for 
* affinity
* SHM
* cmdargs

## Still to go 
* ROCV
* demangle

## Not going to do
Qthreads

**Comment by jonathan-beard** [comment]
Seems to be done. Closing.
