### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [RaftLib/RaftLib#107]
I would like to point out that identifiers like “[`_FIFO_HPP_`](https://github.com/RaftLib/RaftLib/blob/37651eb7533ba62b0a3928783dd2e3784a3cb1f3/raftinc/fifo.hpp#L20 "Update candidate")” and “[`_MAPBASE_HPP_`](https://github.com/RaftLib/RaftLib/blob/2e4493120ec908a81914e05232bcf65d4c1389d7/raftinc/mapbase.hpp#L29 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by letterman9** [comment]
Sure, we can fix. Any chance you could start a pull request? Maybe we should script a replacement and run CI (and likely fix up leftovers from the script)...

Or, is there a better approach you would recommend?

**Comment by jonathan-beard** [comment]
Hmm, seems like a job for Perl. Shouldn’t impact the APi either so...easy change I think.

**Comment by elfring** [comment]
Can [another development tool like “wave”](https://www.boost.org/doc/libs/1_73_0/libs/wave/doc/wave_driver.html "Description for the program “wave”") help to recheck also [the usage of include guards](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by jonathan-beard** [comment]
Fixed, closing issue. I need to go through the OpenCV code as well to double check...but, will do so. I'll upload my Perl hack as a gist too. Might be useful to more people...besides, everybody loves hashes of functions right?

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/RaftLib/RaftLib/commit/44c4b6ecae0909e20a76553d4cc05726a6c316c2 "Renaming of some include guards").
