### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [RaftLib/RaftLib#108]
[An extra null pointer check is not needed in a function](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [the destructor for the class “MapBase”](https://github.com/RaftLib/RaftLib/blob/2e4493120ec908a81914e05232bcf65d4c1389d7/src/mapbase.cpp#L41 "Update candidate").

**Comment by jonathan-beard** [comment]
Sure, @elfring, can you submit a pull request, happy to Merge. If not I can find some time tonight or this weekend. I’m spending most of my evenings working on bringing the benchmarks up to date again.

**Comment by jonathan-beard** [comment]
Actually, looking at an older version of the schedule code. It left the pointer entry for kernels that may have already been deleted in the list and set them to nullptr after the destructor for the kernel was called. At the time, this removed the need for a lock on that list. In the current implementation, this isn't needed. I'll go ahead and fix this over lunch and make a pull request. 

Good catch @elfring, thanks!

**Comment by jonathan-beard** [comment]
Perfect time scope for lunchtime fix, done. Plz follow up if you find any more @elfring. Thanks again!
