### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [RaftLib/RaftLib#111]
I find that include guards like “[`MAP_HPP`](https://github.com/RaftLib/RaftLib/blob/bebfdcfd9924e2d77353fce7a4a7428ba80decae/raftinc/map.hpp#L20)” and “[`PORT_HPP`](https://github.com/RaftLib/RaftLib/blob/bebfdcfd9924e2d77353fce7a4a7428ba80decae/raftinc/port.hpp#L20)” are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by jonathan-beard** [comment]
Ok, we can fix that too. Can you queue up likely candidates? If just a few it might be best to manually update a few headers with more complex names.

**Comment by elfring** [comment]
Thanks for [another improvement around include guards](https://github.com/RaftLib/RaftLib/commit/a835b1b93b99b06e3ede39290bba5c24afe57c66 "Made guards more unique").
