### ISSUE TITLE
Debug detailed Info 

### ISSUE THREAD

**Issue by mocasr** [RaftLib/RaftLib#124]
## Describe the bug
I am having segfault when running raft::map, how can I debug more? 

## Steps To Reproduce
*Re-writing dedup benchmark for Raftlib
* Read Producer(conf, fd, args);
  Write Consumer(conf, fd_out, args);
    
  raft::map m;
  m += Producer >> Consumer;
  m.exe();

## Screenshots
* Below is gdb backtrace
#0 0x0000000000000000 in ?? ()
#1 0x000000000045a913 in std::thread::join() ()
#2 0x0000000000407569 in raft::map::exe<partition_dummy, simple_schedule, dynalloc, basic_parallel> (this=0x7fffffffd260)
  at /home/local/bumblebee/masri/RaftLib/build/raft/include/./raftinc/map.hpp:145
#3 0x0000000000404fe0 in RaftPipeline (targs=0x7fffffffda40) at encoder.h:657

**Additional context**

**Comment by jonathan-beard** [comment]
Will check our code in benchmarks repo...

**Comment by jonathan-beard** [comment]
Looking at the code, 
```
//Allocate a new chunk and create a new memory buffer
chunk = (chunk_t *)malloc(sizeof(chunk_t));
```
in the work function, I'd skip doing that and allocate 
```
auto c(output["out"].template allocate_s<chunk_t>());
```
directly in the work function instead of allocating then copying the pointer, 
the runtime will decide if the size is big enough to do zero copy, pointer
copy or otherwise. That being said, the copy code should run unless
the there's something else going on.

**Comment by jonathan-beard** [comment]
```
In file included from dedup.cpp:12:
encoder.h:339:7: error: jump to case label
  339 |       default:
      |       ^~~~~~~
```
I've gotta fix that before I can debug....or at least get the compiler to stop complaining. 

-J
