### ISSUE TITLE
Download all submodules with code zip download

### ISSUE THREAD

**Issue by jonathan-beard** [RaftLib/RaftLib#141]
**Is your feature request related to a problem? Please describe.**
Feature request related to closed issue #138, all submodules are not auto-downloaded
when using the zip download. When compiling, no .git file is present and an ambiguous
error message results. 

**Describe the solution you'd like**
Either download the code within the cmake or some server side script that would
enable github to package the correct files for download. 

**Describe alternatives you've considered**
1. add a hook in the cmake helper that does the git submodule initialization to check for a .git file first and if none exists then use the cmake download functionality to pull it down.
2. we could simply add a warning in the cmake script to download the appropriate files.

**Additional context**
None

**Comment by mr-j0nes** [comment]
#167 is related to this.

In my opinion submodules are different repos that have to be downloaded separately. They are simply dependencies that have to be treated by the user as any other dependency. Our job is just to indicate such dependencies in the README.md, which we currently do not do :) . We just need to indicate what commit hash is needed to be downloaded. 

As those dependencies belong to the RaftLib namespace, a nice to have would be to release those dependencies (demangle, affinity, etc.) with a version number and to indicate what version is needed by the RaftLib library, but for now stating the commit hash is enough.

Anyway, as described in the linked issue above, git-archive, used by GitHub to create the zip/tarball bundle and maintained by the git team, could be in charge of downloading also submodules. This is something that has been requested, so let's see if someday it's implemented.

So, if you are fine, I guess the only thing we need to do is just to update the README.md..
