### ISSUE TITLE
rbzip2 with Qthreads hanging/crashing

### ISSUE THREAD

**Issue by EmeraldShift** [RaftLib/RaftLib#146]
## Describe the bug

Running the rbzip2 benchmark (from [here](https://github.com/RaftLib/benchmarks)) on RaftLib compiled with Qthreads produces unexpected behavior.

1) Running rbzip2 with `QTHREAD_NUM_SHEPHERDS=1` and the command-line argument `-th 1` hangs.
2) Running rbzip2 with `QTHREAD_NUM_SHEPHERDS=15` and the command-line argument `-th 5` raises a segmentation fault.

## Steps To Reproduce
```
# Pull RaftLib, Qthreads, and the benchmarks
git clone https://github.com/RaftLib/RaftLib raftlib
git clone https://github.com/RaftLib/qthreads
git clone https://github.com/RaftLib/benchmarks

# Compile Qthreads
cd qthreads
libtoolize && aclocal && autoconf && autoheader && automake --add-missing && ./configure --disable-internal-spinlock && make clean && make -j$(nproc) && make -j check && sudo make install
ldconfig
cd ..

# Compile RaftLib with Qthreads
cd raftlib
mkdir build
cd build
cmake -DUSEQTHREAD=1 ..
make -j$(nproc) install
cd ../..

# Compile and prepare the rbzip2 benchmark
cd benchmarks/parallel-bzip/rbzip2
PKG_CONFIG_PATH=/usr/local/pkgconfig ./build.sh build
wget https://homepages.cae.wisc.edu/~ece533/images/monarch.png

# Expose the issue: this sometimes segfaults, sometimes aborts
QTHREAD_NUM_SHEPHERDS=15 ./rbzip2 -i monarch.png -o /dev/null -th 5

# Expose the issue: this hangs
QTHREAD_NUM_SHEPHERDS=1 ./rbzip2 -i monarch.png -o /dev/null -th 1
```

## Expected behavior
The program terminates successfully, and nearly instantly (since the file to compress is so small)

## Unexpected behavior
In the hanging case, one thread is calling `std::thread::join()` from the `raft::map::exe` call, while the another thread appears to be stuck in the `while` loop at the bottom of `dynalloc::run`., another is stuck in `pool_schedule::start`, and another is stuck in `basic_parallel::start`.

Replacing the `m.exe()` call near the bottom of `rbzip2.cpp` with `m.exe<partition_dummy, pool_schedule, stdalloc, no_parallel>()` changes the behavior: one thread is calling `std::thread::join()` from the `raft::map::exe` call, while the pool scheduler (the only other running thread) appears to be stuck in the `AGAIN` loop in `pool_schedule::start`. The `tail` vector contains a single element (I _think_ it's the `filewrite` kernel), with `finished` set to false--but I don't think the kernel is actually running anymore.

## Platform
AArch64, 16 cores, running on a SolidRun HoneyComb LX2K. Running Ubuntu 20.04.1 on Linux 4.19.61

**Comment by EmeraldShift** [comment]
Possibly related to this, there seems to be a bug in `RingBufferHeap` which causes non-resizing buffers to never yield in the `for(;;)` loop: https://github.com/RaftLib/RaftLib/blob/ef310fabc53ae3523688f0c1e9453ca29400d777/raftinc/ringbufferheap.tcc#L781 Fix incoming...

**Comment by jonathan-beard** [comment]
Will close this one once I verify that the fix actually corrects this one as well, it should....

**Comment by janciesko** [comment]
Did the fix resolve the issue?

**Comment by jonathan-beard** [comment]
Yes, seemingly. I was creating a few more test cases to see if we can stress more, but....it fixes for all the cases that were previously failing. Will go ahead and close.
