### ISSUE TITLE
No such file or directory error for "raftutility". (example1.cc:9:10: fatal error: raftutility: No such file or directory)

### ISSUE THREAD

**Issue by ameyand98** [RaftLib/RaftLib#155]
## Describe the bug
After pulling the latest changes for the hh.hpp fix, the code still doesn't compile due to this error for raftutility. Upon inspection, I don't see the installation of raftutility in my /usr/local/include directory where other files (like raft, raftio, etc.) are installed, and neither does it say anything in the installation log. Not sure if this just requires a small change in the makefile but wanted to bring it to attention. 

## Steps To Reproduce
after latest branch installation, try compiling any example code (like the vector sum) that includes raftutility 

## Expected behavior
RaftLib to compile

**Comment by jonathan-beard** [comment]
Yeah, let's fix this one too. I should add some test cases to make sure that this is included.

**Comment by jonathan-beard** [comment]
fix merged.

**Comment by ameyand98** [comment]
Great, it works now, thank you!
