### ISSUE TITLE
Addressing Feedback from CppCon presentation proposal

### ISSUE THREAD

**Issue by jonathan-beard** [RaftLib/RaftLib#19]
I'm looking for some good feedback, on perhaps the hardest part of any open source software project....documentation. 

One review in particular is a bit worrisome for me, since the library is intended to be "intuitive" and easy to use. It was also the only non-accept rating, being "borderline." From the RaftLib org members (and the web in general) are there any improvements we can make to the documentation (either the raftlib.io front page, the wiki, or through more blogposts perhaps) to make RaftLib easier to use and understand from the start? The review in question is below and please respond directly via comments (as always, be respectful and constructive). Thanks!!

> I was disappointed in the level of description, examples, etc in the Raftlib information I found.  Given that I'm at least somewhat familiar with the topic I expected that I would "get" it right away. It was harder than I thought it should be.  Also there is no mention of other approaches - HPX for example.  I think I know what he means by "Streams" but maybe I don't.  Of course this is partly due to the usage of "stream" in the standard library which has a clear meaning - but I'm hoping the authors "Streams" aren't related.  There are a number of data flow implementation methods that I'm thinking are more promising - in particular the Standard library ranges proposal in development.   I have the feeling that this is a work in progress rather than something that programmers are expected to be able to use right now.

**Comment by pl53** [comment]
Here is my thought.

The new description is very informative, albeit "concurrency" doesn't tell the full picture. "parallelism" might be more accurate. For audience from the academic world, linking RaftLib to a well-known parallel computing model can help them quickly understand it. Communication Sequential Processes (CSP) looks to be a close one, but I haven't verified that formally.

To help potential users get started, a step-by-step tutorial is necessary. On top of that, a cook book that provides examples for common application patterns would also be helpful.

**Comment by jonathan-beard** [comment]
Take a swag at incorporating more of a "parallelism" connotation. Take a look at the wiki, I'm wondering how far we are from a true step by step tutorial? I'd been reticent to write too much as we're still in alpha stage.
