### ISSUE TITLE
what is `#include <cmd>`?

### ISSUE THREAD

**Issue by sangli00** [RaftLib/RaftLib#23]
source : examples/general/pi/pisim.cpp

error detail:
RaftLib-RaftLib-d6e6fa3/examples/general/pi/pisim.cpp:29:15: fatal error: cmd: No such file or directory
 #include <cmd>

I can't find any about  cmd info.

**Comment by sangli00** [comment]
wo....  I find it .

https://github.com/RaftLib/cmdargs

**Comment by jonathan-beard** [comment]
Likely need to fix that if it didn't auto install with the library build.

Thanks!

**Comment by sangli00** [comment]
I think,README add this package detail info.
Yes,I refer to README cmake this build.

**Comment by jonathan-beard** [comment]
ok, I think we've gotten this one fixed. I'll add to the readme. I'm also adding a .pc file to make it easier to build outside the initial clone and cmake so that all needed libraries will be linked with pkg-config on linux/unix based systems.
