### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#36]
It seems there are some memory leaks in the library.

`valgrind --leak-check=full ./sumapp`

**Comment by jonathan-beard** [comment]
Ok, ran 
```bash
==9822== 
==9822== LEAK SUMMARY:
==9822==    definitely lost: 288 bytes in 6 blocks
==9822==    indirectly lost: 864 bytes in 12 blocks
==9822==      possibly lost: 0 bytes in 0 blocks
==9822==    still reachable: 72,704 bytes in 1 blocks
==9822==         suppressed: 0 bytes in 0 blocks
==9822== Reachable blocks (those to which a pointer was found) are not shown.
==9822== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

Comes from this.....not a huge issue if we don't create a lot of ports, however needs to be fixed. Will adjust destructor to delete the allocation here (line 282 from port.hpp) on obj destruction:

```cpp
pi.const_map.insert( std::make_pair( Type::Heap , new instr_map_t() ) );
```

**Comment by jonathan-beard** [comment]
[UPDATE] - 01.07.17
* patch ready, 
* testing on pthreads and qthreads passes on Linux
* same for OS X
* will test with Windows once I get registry error in visual studio fixed

**Comment by mr-j0nes** [comment]
Thanks for the quick reaction. When you have time take a look at the other issues I posted.

**Comment by jonathan-beard** [comment]
I'll have time to check it out today. Might not have time to finish them all, but I'll at least triage. Any chance you'd like to be a contributor too?

**Comment by mr-j0nes** [comment]
I thought I contributed already :) Actually I was thinking taking a look at the memory leak issue myself but you solved it in no time. I'm quite busy with my own project right now but I'll see if I can get more familiar with the library to contribute..

My other issues are actually no issues, just a couple of questions and wishes, no need any hurry..

**Comment by jonathan-beard** [comment]
Commit #6b9adf77563e78e00fa020117eac33d786021c79 fixed the memory leak. There are 72-bytes outstanding still reachable, however, those should be reachable. I'll apply the patch to the dev branch as well and check out the other issues. 

No worries. We're all busy. Figured it couldn't hurt to go fishing for contributors. Thanks again for catching!,
-Jonathan
