### ISSUE TITLE
More memory leaks

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#37]
Thanks for fixing the previous leak, now it works fine. 
I have found a couple more:

`valgrind --leak-check=full ./readtest cmake_install.cmake`
`valgrind --leak-check=full ./rbzip2 -i alice.txt -o alice.bz`

**Comment by jonathan-beard** [comment]
Hah...thanks! I'll fix this one tonight.

**Comment by jonathan-beard** [comment]
fixed...part of it was I left out on the options dialogue destroying the options at exit, didn't make much of a difference but a few cycles off the program exit. The main bug was in the garbage collection for large objects, fixed now runs with zero leaks for large objects.
