### ISSUE TITLE
Some macro definitions make problems

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#40]
The header file `/usr/local/include/raftinc/kernelpreempt.hpp`

defines following macro `#define restore( k ) longjmp( k->running_state, 1 )`

"restore" is a keyword that anybody could use in their code.
Being defined as a macro can cause some problems later on.

For example when including some boost header files I get following error message:

>/usr/include/boost/io/ios_state.hpp:47:11: error: expected identifier before ‘->’ token
>     void  restore()

The code at that line gets messed up with the previous macro
`    void  restore()
        { s_save_.flags( a_save_ ); }`

So maybe Raftlib can define  macros in a more unique way, say e.g. with a namespace ? Maybe as 
`#define RAFTrestore( k ) longjmp( k->running_state, 1 )`

**Comment by jonathan-beard** [comment]
yeah, I'm getting rid of these. I just removed the jmp code, no point in having the macro. The Sandia QThreads lib provides a nice user space threading library that is relatively cross-platform. No point in rolling my own.

**Comment by jonathan-beard** [comment]
Closing issue, fixed. I'm working through the code to remove all macros where possible. The time, I think, has come where C++ code no longer really needs them save for a few select instances.
