### ISSUE TITLE
Exception when unused output port but segmentation fault when unused input port

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#41]
Test done on `sumapp.cpp` example:

if I add one output port
`      output.addPort< T  >( "sum", "test"     );`

as expected I get an exception:
> terminate called after throwing an instance of 'AmbiguousPortAssignmentException'
>  what():  One port expected, more than one found!
>Output port from source kernel (Sum<long>) has more than a single port.

but if I add another input port:
`      input.addPort<  T > ( "input_a", "input_b", "test" );`

I get a segmentation fault.

Not sure if that is the right behavior?

**Comment by mr-j0nes** [comment]
Not sure if you prefer to have a second issue created for this, but also segmentation fault when there are no ports added. E.g. in `sumapp.cpp` :

`      input.addPort<  T > ( "input_a", "input_b");`
`      // output.addPort< T  >( "sum"     );`

It would have saved me some debugging time if there was an exception :)

**Comment by jonathan-beard** [comment]
Should definitely be an exception. Also, 2nd issue makes it easier to track.

**Comment by mr-j0nes** [comment]
Done. Thanks a lot Jonathan..

**Comment by jonathan-beard** [comment]
Now throws an exception if any port is double initialized.
