### ISSUE TITLE
bad alloc exception instead of own library exception when no output ports

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#42]
E.g. in `sumapp.cpp` :

`input.addPort< T > ( "input_a", "input_b");`
`// output.addPort< T >( "sum" );`

The error message:

> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc

Expected is to have an exception from the library itself pointing out that the problem is the missing output port.

**Comment by jonathan-beard** [comment]
That is also the expected behavior. I need to write some test cases for all the exceptions.

**Comment by jonathan-beard** [comment]
This one is fixed. There was a bug in the code that was causing only the output ports to be checked within the BFS through the graph. I updated to be a linear search given a BFS is overkill while I was fixing the bug. It's now a bit faster and also catches this case.
