### ISSUE TITLE
One input split in several outputs

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#48]
Hey Jonathan, hope you're doing well..

Say we have `A >> B >> C`
`A` sends one message to `B`.
`B` then splits this message into several hundreds of other messages that needs to send to `C`.

The problem I face is the following:

If I return `raft::proceed` after `B` sends a message to `C`, then the framework does not start `B` again (because `B` already consumed the input message from `A`)

If `B` sends all messages to `C` in a loop without returning `raft::proceed` it might happen that the queue gets saturated with so many messages.

So what is the best way to proceed in this scenario ?

Thanks in advance..

**Comment by mr-j0nes** [comment]
Never mind this question, I solve this with a design change..

**Comment by jonathan-beard** [comment]
Hi. I have a quick question on this. So....can you give me an example where B would need to fire without getting an input from A? Just curious about this one before we close it entirely. 

Thanks!,
Jonathan

**Comment by mr-j0nes** [comment]
This was nonsense from my side. I was playing with the idea of A sending some kind of container to B, e.g. a file, and then B opening and sending each of the elements in the container to C.
This is not B's job, but A's.

**Comment by jonathan-beard** [comment]
Aah.  That pattern can definitely work. So A sends the filename to B, B, reads the elements from the file and sends them to C. The trick is to not call return until you've completed reading from the file. That however, could be non-optimal for scheduling. Perhaps you've pointed out something that we can queue up to improve. IO is one of those tricky things that where enabling the scheduler to swap on ld stall would be useful, so having something in between would be nice.

**Comment by mr-j0nes** [comment]
Well, at the time I got to the conclusion that a stream of kernels should manage homogeneous types of elements. When the need comes to manage non-homogeneous types of elements then the stream should be split. In the end, after a redesign, I ended up not needing any of this. But anyway if someday this pattern is offered, out of the box, by the library, it would be indeed a nice thing.

**Comment by mr-j0nes** [comment]
Guess what, I ended up needing this scenario for same type of elements.

So `B` (from above) receives one element from `A` and creates e.g. 10  out of that one and sends them to `C`.

The way I do it is very simple, I just peek() the incoming element but I don't recycle() it until I send all created elements out: After sending each of the created elements I return raft::proceed. When run() is called I check if the list of created elements is empty. if yes I recycle(1), And with this logic I can create as many elements without saturating the output port.

So this issue can be closed now..
