### ISSUE TITLE
Fix or suppress -Waligned-new warnings in GCC 7 build

### ISSUE THREAD

**Issue by badair** [RaftLib/RaftLib#50]
From GCC 7 [release notes](https://www.gnu.org/software/gcc/gcc-7/changes.html):
* C++17 support for new of over-aligned types can be enabled in other modes with the -faligned-new flag
* -Waligned-new has been added to the C++ front end. It warns about new of type with extended alignment without -faligned-new

**Comment by jonathan-beard** [comment]
Will update on dev branch first then carry those to the main branch.

**Comment by jonathan-beard** [comment]
fixed.
