### ISSUE TITLE
Prevent kernel to be scheduled if it has empty inputs

### ISSUE THREAD

**Issue by sogartar** [RaftLib/RaftLib#64]
I have a graph with many kernels. Some of them have more than one input port. They are being called if there is an input on one of the ports. Is it possible to configure the scheduler to call them only when there is input on all the ports?
I envision that a derived `kernel` class could specify during construction which port is aways required to have input.

**Comment by mr-j0nes** [comment]
Hi there, just another user here. 

As I see for the kernels having more than one input port you could just loop all the input ports. If all of them have data then you can continue with your logic, if not just return `raft::proceed` and do the same next time the kernel is called.

You can check if a port has data with the `size()` method bigger than 0.

**Comment by sogartar** [comment]
You would have to move the data into internal queues as this would cause the kernel to be constantly scheduled.

**Comment by jonathan-beard** [comment]
it is possible. All the ports are checked regardless by the scheduler. I'll code something up and commit, shouldn't take but a few minutes to make this work. The schedule.cpp has the base scheduler routine that is called by all _kernelRun_ so I'll start there.

**Comment by jonathan-beard** [comment]
Okay, delay of game for family...I've pushed a patch that will do what you'd like @sogartar and @mr-j0nes . There's a way more efficient way to implement the mask on the ports too. It's super easy to check and see if something is "empty", however, the current patch uses size. I need to add the "empty" function as it's required by the gpgpu private branch anyways. I'll try tonight, if not I'll do really early AM tomorrow.

**Comment by jonathan-beard** [comment]
pushed patch to master for the fix....will update documentation as well.
