### ISSUE TITLE
Stack corruption issue with Sandia QThreads + RaftLib (main branch) on OS X (High Sierra only)

### ISSUE THREAD

**Issue by jonathan-beard** [RaftLib/RaftLib#65]
Looks like on High Sierra there's a stack corruption issue when combined with qthreads 1.13. Works well on all other os x distros. I've had a few emails about this condition, wanted to add an official issue so we can work to debug in an open way.

**Comment by jonathan-beard** [comment]
Bug is actually in the qthreads library, will send them a pull request to fix tomorrow, but it really boils down to accidentally putting critical code inside assert statements like so [link](https://godbolt.org/z/wSgTU_). On most boxes, assert.h looks something like:

```c
 55 #ifdef NDEBUG
 56 #define assert(e)   ((void)0)
 57 #else
```

which makes **e** go away.

**Comment by benman1** [comment]
It'd be helpful if you could fix this in the RaftLib/qthreads repo. I compiled qthreads from there assuming it would be the one most likely to work.

**Comment by benman1** [comment]
I [can't see any pull request from you regarding this](https://github.com/Qthreads/qthreads/pulls). Is this something you are working on?

**Comment by jonathan-beard** [comment]
Hi @benman1, I'm re-opening this one. This should have been done awhile ago. Unfortunately I didn't re-open the issue. Doing so now so I remember to fix the debug assert.

**Comment by jonathan-beard** [comment]
@benman1, qthread seems to work now with version applied (Linux only), however, when using C++ exceptions, those aren't well handled as the qthreads stack frame doesn't quite unwind in a way that agrees with them (working on figuring out a solution).
