### ISSUE TITLE
Question: Raftlib using too high cpu, need improve?

### ISSUE THREAD

**Issue by zheliu1113** [RaftLib/RaftLib#67]
Hi,

I am using raftlib for my program, and I found it is using up too much cpu, I want to know if there is anyone facing same issue? Or is there any tricks or setting I ignored, which may cause this problem?

To make sure it is raftlib using my cpu, I ran the "raftlib hello world" test program offered here:
https://gist.github.com/jonathan-beard/6a2fe1d9796cb7bb102cb8b34800fff1

And still it use over 100% cpu (Shown by command 'top' below). But there is no infinite loop or any calculation.
(The top one is raftlib hello world, 104%)
![image](https://user-images.githubusercontent.com/34725558/42402972-1fdcd684-814c-11e8-91ae-9c6c0b23bd94.png)
Please give me some advice about this problem, any discussions are welcomed.

Best,
LIU Zhe

**Comment by sh22tan** [comment]
Seeing the same behaviour on my side.
