### ISSUE TITLE
Example doesn't build on Windows 10 under VS2017

### ISSUE THREAD

**Issue by Cthutu** [RaftLib/RaftLib#68]
One of the examples doesn't build under Windows 10 using VS2017.  The error is in examples/general/pi/pisim.cpp because it tries to `#include <cmd>`, which doesn't exist on my system.

I generated the solution with default CMake parameters, using Win64 version of VS2017.  I built the Debug build.

**Comment by jonathan-beard** [comment]
Ok, adding in the cmd library seems to solve the issue (built and ran on vs2017 virtual machine). Please let me know if adding the library to your path doesn't solve the issue. The library is included in the RaftLib organization repository.
