### ISSUE TITLE
Doesn't build under VS2017 when using allocate_s<string>

### ISSUE THREAD

**Issue by Cthutu** [RaftLib/RaftLib#70]
fifo.hpp fails to build when using this code:

`auto c(output["sum"].template allocate_s<string>());`

There use of `__attribute__((__unused__))` is GCC only and doesn't compile under MSVC.  I would suggest replacing all of these attributes with a macro (like `RAFTLIB_UNUSED`), which can be blank under MSVC.

**Comment by jonathan-beard** [comment]
seems to work for me, however, I have a lot of custom defines. Any chance you can create a pull request for this option? I will happily check it out and approve. 

Thanks!
