### ISSUE TITLE
Graph with loop does not exit

### ISSUE THREAD

**Issue by sogartar** [RaftLib/RaftLib#72]
If there is a loop in the graph it seems the stop signal is not propagated through the graph and it never exits.
For example if we have something like
```c++
...

raft::map m;

m += a >> b["in1"] >> c >> b["in2"];

m.exe(); // This never returns even if a returns raft::stop in run()
```

**Comment by jonathan-beard** [comment]
Will work on this one tonight. The credit should be passed, definitely a bug.

**Comment by jonathan-beard** [comment]
Implemented **potentially better long-term solution 1**, working to add in solution 3 above as well, but for now this should fix the issue so closing this one. 

Thanks for finding this, definitely helps out the framework overall!
