### ISSUE TITLE
Deadlock when one of the output ports is not linked

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#73]
Hey Jonathan,

hope you are doing alright.

I have following problem:

- I have a kernel to which I add an extra output port which I forget to link to another kernel.
- On exe() the runtime finds the non-mapped port and throws correctly the PortUnconnectedException.
- In the MapBase destructor when trying to acquire, the mutex cannot be locked and stays the in the loop (in this line: `auto &container( all_kernels.acquire() );`)

Unfortunately I have the issue when called from my application and I cannot recreate it with a simple program, so I wonder if you could spot the problem with only this description..

In the meantime I'll try to recreate it with some few lines of code..

Thanks a lot in advance..

**Comment by mr-j0nes** [comment]
Ok I think the problem is following:

In `src/map.cpp` there is this code:

```
void
raft::map::checkEdges()
{
    auto &container( all_kernels.acquire() );
    /**
     * NOTE: will throw an error that we're not catching here
     * if there are unconnected edges...this is something that
     * a user will have to fix.  Otherwise will return with no
     * errors.
     */
    /** 
     * the old version used a BFT, this one uses a much 
     * more efficient linear search through the graph
     */
    for( auto &k : container )
    {
        /** 
         * NOTE: This will throw an exception
         * of type PortUnconnectedException
         */
        k->allConnected();
    }
    all_kernels.release();
    return;
}
```

So what happens is following:
- aquire()
- allConnected()  <-- here there is a PortUnconnectedException.
- release()            <-- The release does not run and the mutex stays locked.
- The exception triggers the MapBase's destructor which in turn tries to aquire() the mutex that was never released.

To avoid this maybe it would be good to implement something like `std::lock_guard` ?

Cheers..

**Comment by jonathan-beard** [comment]
That’s not a bad idea at all. Want to take a crack at the patch?

**Comment by jonathan-beard** [comment]
Thanks @mr-j0nes, that'll work.
