### ISSUE TITLE
Fix declaration of map in wiki page "Philosophy"

### ISSUE THREAD

**Issue by gkasten** [RaftLib/RaftLib#75]
I cloned the wiki and fixed this locally, but then could not figure out how to offer it to you as a pull request. So instead I am instead creating an issue with the patch:

diff --git a/Philosophy.md b/Philosophy.md
index 21a7eb4..d5d7daa 100644
--- a/Philosophy.md
+++ b/Philosophy.md
@@ -59,7 +59,8 @@ Which seems simple enough. Lets break down what needs to happen:
   kernel  stoch_function /** 8 input ports **/;
   kernel  print;
   //make 8 of gaussian, link then to stoc_function, stream to print
-  raft::map += gaussian >= stoch_function >> print;
+  raft::map m;
+  m += gaussian >= stoch_function >> print;
   ```
 
   we must have a function that traverses the graph to:

**Comment by jonathan-beard** [comment]
Edited online....thanks for the update!
