### ISSUE TITLE
Is raftinc/optdef.hpp needed ?

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#79]
Hi Jonathan,

hope you are doing alright. The file `raftinc/optdef.hpp` has two macros: `likely `and `unlikely` that interfere when compiling with the newer boost libraries. The file `boost/date_time/special_values_parser.hpp` contains a function called `likely` too which gets replaced with the macro content. 

I don't see these macros used anywhere in the code of Raftlib, so the question is, are they really needed ? If not can we remove the header file ? If yes can we add namespace to the macros .e.g. RAFTLIB_LIKELY ?

Thanks in advance,

**Comment by jonathan-beard** [comment]
It appears trust one is orphaned code. I had the same issue awhile back and so those refs have been moved to defs.hpp and renamed to R_XX vs bare keywords. I wanted separate macros in case I felt adventurous in the future and did something other than the standard macro. If you have time, could you submit a pull without the file (after you make sure it build)? If not, won’t take too long, should be able to tonight or this weekend. I’ll also double check to make sure it’s not in the parser-improvement branch (got fed up with the DSL parser so I’m rewriting it slowly but surely).

**Comment by jonathan-beard** [comment]
Fixed! :)

**Comment by mr-j0nes** [comment]
Hi Jonathan, thanks for the super quick reaction.
