### ISSUE TITLE
Questions about Raftlib

### ISSUE THREAD

**Issue by ricardopieper** [RaftLib/RaftLib#81]
Hi,

I'm making a study of stream processing tools, and I have some questions about Raftlib. I've been studying tools like Spark, Flink, Samza, etc... and I want to know the extent in which Raftlib is comparable to them.

In the thesis, it is briefly mentioned Raftlib capabilities in regards to distributed stream computing. Specifically, it is mentioned that there is an "oar" component that manages a network mesh.

I'd appreciate if you could answer these questions:

1 - Seems like the networking capabilities of Raftlib are poorly documented, or maybe not obviously available. Is there more information on this? Maybe I just didn't find it.

2 - Suppose I want a kernel to spit out a stream of a custom type. Like a `class PurchaseEvent` or something like that, with many properties. How should I deal with serialization in these cases, when I have multiple nodes in a network and some of these events travel between computers? Should my kernel just return a byte stream or something, and deserialize in the other side?

3 - Is my understanding correct that Raftlib automatically handles back-pressure? I understood that RaftLib automatically optimizes resource allocation for all kernels, and when this is detected, an automatic action takes place. Are there any chances that a node executing some raftlib kernels could suffer resource exhaustion because a kernel is misbehaving?

4 - Normally tools like Flink, Samza, Spark, etc... mention their guarantees regarding message processing or message delivery (is a bit of a muddy definition) in terms of "at-most-once/best effort", "at-least-once", "exactly-once", etc etc. I think this concern is more important in a commercial, enterprise setting than an academic one. Regardless, does raftlib make any guarantees regarding message delivery between network nodes?

**Comment by jonathan-beard** [comment]
> Seems like the networking capabilities of Raftlib are poorly documented, or maybe not obviously available. Is there more information on this? Maybe I just didn't find it.
*  There's a TCP socket version of the FIFO. Over the years it has been removed as keeping it up would require significant work. If it's interesting enough, we can add back, although perhaps plugging in an RDMA style layer might actually be better. The SHM version is in the same boat, although I'm making an effort to bring that back given it's needed to even start on the TCP socket version. 

> Suppose I want a kernel to spit out a stream of a custom type. Like a `class PurchaseEvent` or something like that, with many properties. How should I deal with serialization in these cases, when I have multiple nodes in a network and some of these events travel between computers? Should my kernel just return a byte stream or something, and deserialize in the other side?

* From a programmer perspective, you just write a struct or class into the stream, the runtime will take care of the rest. 

> Is my understanding correct that Raftlib automatically handles back-pressure? I understood that RaftLib automatically optimizes resource allocation for all kernels, and when this is detected, an automatic action takes place. Are there any chances that a node executing some raftlib kernels could suffer resource exhaustion because a kernel is misbehaving?
* At the moment, yes, you could encounter user-limits if a kernel is misbehaving. That being said, there are limits as to what the runtime can allocate so in reality, the likelihood is slim. But, definitely something we're still working on. 

> Normally tools like Flink, Samza, Spark, etc... mention their guarantees regarding message processing or message delivery (is a bit of a muddy definition) in terms of "at-most-once/best effort", "at-least-once", "exactly-once", etc etc. I think this concern is more important in a commercial, enterprise setting than an academic one. Regardless, does raftlib make any guarantees regarding message delivery between network nodes?
