### ISSUE TITLE
Windows fix for helpers/cacheinfo.cpp

### ISSUE THREAD

**Issue by brechtsanders** [RaftLib/RaftLib#90]
I noticed L1D_CACHE_LINE_SIZE was not set to a power of 2 when building release a8 on Windows with MinGW-w64. The problem was that helpers/cacheinfo.cpp wasn't returning the the actual cache line size. Also there was a typo in the conditional for the Windows section.
The following patches fixes this:
```
patch -ulbf helpers/cacheinfo.cpp << EOF
@@ -30,3 +30,3 @@
 #include <unistd.h>
-#elif _WIND32
+#elif _WIN32
 #include <windows.h>
@@ -87,3 +87,3 @@
     }
-    std::cout <<  i;
+    std::cout << line_size;
     free(buffer);
EOF
```

**Comment by jonathan-beard** [comment]
I'll apply patch shortly, thanks!

**Comment by jonathan-beard** [comment]
Took me a moment to figure out...the patch is apparently off the previous A-8 release code. I've pulled out A-9 from the latest master as a new (and last) alpha release before we move to beta. The code has quite a few improvements since we last released it. Thanks for the help! 

-J
