### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by jonathan-beard** [RaftLib/RaftLib#94]
We definitely need to set up Windows CI, any takers to own this?

**Comment by f-tischler** [comment]
I'll take a look at it. Haven't done much with Travis yet

**Comment by f-tischler** [comment]
As @mr-j0nes pointed out, we could use Github actions. When #97 is merged I will submit a PR for this.

**Comment by jonathan-beard** [comment]
Perfect. Looks like it's merged and CI is building. Looking at CI I probably need to broaden that as well.

**Comment by jonathan-beard** [comment]
Fixed by merge #99
